# Site settings
title: Anthony Fiddes
description: Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Anthony Fiddes
user_title: Software Engineer
email: anthony@fiddes.dev
github_username: Anthony-Fiddes

exclude: ['package.json', 'src', 'node_modules']
